[ { path: '/Users/sena/Documents/projects/vue-loader-test/node_modules/css-loader/index.js',
    query: '??ref--1-1',
    options: { sourceMap: true },
    ident: 'ref--1-1',
    normal: [Function],
    pitch: undefined,
    raw: undefined,
    data: null,
    pitchExecuted: true,
    normalExecuted: false,
    request: [Getter/Setter] },
  { path: '/Users/sena/Documents/projects/vue-loader-test/vueLoader/lib/loaders/stylePostLoader.js',
    query: '',
    options: undefined,
    ident: undefined,
    normal: [Function],
    pitch: undefined,
    raw: undefined,
    data: null,
    pitchExecuted: true,
    normalExecuted: false,
    request: [Getter/Setter] },
  { path: '/Users/sena/Documents/projects/vue-loader-test/sassLoader/lib/loader.js',
    query: '??ref--1-2',
    options: { sourceMap: true },
    ident: 'ref--1-2',
    normal: [Function: sassLoader],
    pitch: undefined,
    raw: undefined,
    data: null,
    pitchExecuted: true,
    normalExecuted: false,
    request: [Getter/Setter] },
  { path: '/Users/sena/Documents/projects/vue-loader-test/vueLoader/lib/index.js',
    query: '??vue-loader-options',
    options: {},
    ident: 'vue-loader-options',
    normal: 
     { [Function]
       VueLoaderPlugin: { [Function: VueLoaderPlugin] NS: 'vue-loader' } },
    pitch: undefined,
    raw: undefined,
    data: null,
    pitchExecuted: true,
    normalExecuted: true,
    request: [Getter/Setter] } ]